package dev.ebpf.dsl.maps

import dev.ebpf.dsl.kernel.KernelVersion

enum class MapType(val cName: String, val typeId: Int, val minKernel: KernelVersion = KernelVersion.V4_18) {
    HASH("BPF_MAP_TYPE_HASH", 1),
    ARRAY("BPF_MAP_TYPE_ARRAY", 2),
    PROG_ARRAY("BPF_MAP_TYPE_PROG_ARRAY", 3),
    PERF_EVENT_ARRAY("BPF_MAP_TYPE_PERF_EVENT_ARRAY", 4),
    PERCPU_HASH("BPF_MAP_TYPE_PERCPU_HASH", 5),
    PERCPU_ARRAY("BPF_MAP_TYPE_PERCPU_ARRAY", 6),
    STACK_TRACE("BPF_MAP_TYPE_STACK_TRACE", 7),
    LRU_HASH("BPF_MAP_TYPE_LRU_HASH", 9),
    LRU_PERCPU_HASH("BPF_MAP_TYPE_LRU_PERCPU_HASH", 10),
    LPM_TRIE("BPF_MAP_TYPE_LPM_TRIE", 11),
    ARRAY_OF_MAPS("BPF_MAP_TYPE_ARRAY_OF_MAPS", 12),
    HASH_OF_MAPS("BPF_MAP_TYPE_HASH_OF_MAPS", 13),
    DEVMAP("BPF_MAP_TYPE_DEVMAP", 14),
    SOCKMAP("BPF_MAP_TYPE_SOCKMAP", 15),
    CPUMAP("BPF_MAP_TYPE_CPUMAP", 16),
    CGROUP_STORAGE("BPF_MAP_TYPE_CGROUP_STORAGE", 19, KernelVersion(4, 19)),
    RINGBUF("BPF_MAP_TYPE_RINGBUF", 27, KernelVersion.V5_8),
}
