// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

#define MAX_ENTRIES 10240
#define MAX_SLOTS 27

static __always_inline __u32 log2l(__u64 v) {
    __u32 r = 0;
    while (v > 1) {
        v >>= 1;
        r++;
    }
    return r;
}

struct req_key {
    __u64 req_ptr;
};

struct req_info {
    __u64 start_ts;
    __u64 cgroup_id;
};

struct hist_key {
    __u64 cgroup_id;
};

struct hist_value {
    __u64 slots[27];
    __u64 count;
    __u64 sum_ns;
};

struct cgroup_key {
    __u64 cgroup_id;
};

struct counter {
    __u64 count;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 10240);
    __type(key, struct req_key);
    __type(value, struct req_info);
} req_info SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct hist_key);
    __type(value, struct hist_value);
} bio_latency SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct counter);
} bio_count SEC(".maps");

SEC("kprobe/blk_mq_start_request")
int kprobe_blk_mq_start_request(struct pt_regs *ctx)
{
    __u64 rq = (unsigned long)PT_REGS_PARM1(ctx);
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    __u64 ts = bpf_ktime_get_ns();
    struct req_key var_0 = {};
    var_0.req_ptr = rq;
    struct req_info var_1 = {};
    var_1.start_ts = ts;
    var_1.cgroup_id = cgroup_id;
    bpf_map_update_elem(&req_info, &var_0, &var_1, 0);
    return 0;
}

SEC("kprobe/blk_mq_end_request")
int kprobe_blk_mq_end_request(struct pt_regs *ctx)
{
    __u64 rq = (unsigned long)PT_REGS_PARM1(ctx);
    struct req_key var_0 = {};
    var_0.req_ptr = rq;
    struct req_info *entry_1 = bpf_map_lookup_elem(&req_info, &var_0);
    if (entry_1) {
        __u64 delta_ns = (bpf_ktime_get_ns() - entry_1->start_ts);
        struct cgroup_key var_2 = {};
        var_2.cgroup_id = entry_1->cgroup_id;
        struct counter *entry_3 = bpf_map_lookup_elem(&bio_count, &var_2);
        if (entry_3) {
            __sync_fetch_and_add(&entry_3->count, 1ULL);
        } else {
            struct counter var_4 = {};
            var_4.count = 1ULL;
            bpf_map_update_elem(&bio_count, &var_2, &var_4, 1);
        }
        struct hist_key var_5 = {};
        var_5.cgroup_id = entry_1->cgroup_id;
        struct hist_value *entry_6 = bpf_map_lookup_elem(&bio_latency, &var_5);
        if (entry_6) {
            __u32 slot = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
            __sync_fetch_and_add(&entry_6->slots[slot], 1ULL);
            __sync_fetch_and_add(&entry_6->count, 1ULL);
            __sync_fetch_and_add(&entry_6->sum_ns, delta_ns);
        } else {
            __u32 slot2 = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
            struct hist_value var_7 = {};
            var_7.count = 1ULL;
            var_7.sum_ns = delta_ns;
            __s32 _arr_set = (var_7.slots[slot2] = 1ULL, (__s32)0);
            bpf_map_update_elem(&bio_latency, &var_5, &var_7, 1);
        }
        bpf_map_delete_elem(&req_info, &var_0);
    }
    return 0;
}
