// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

struct cgroup_key {
    __u64 cgroup_id;
};

struct dc_stats {
    __u64 refs;
    __u64 slow;
};

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct dc_stats);
} dc_stats SEC(".maps");

SEC("kprobe/lookup_fast")
int kprobe_lookup_fast(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct dc_stats *entry_1 = bpf_map_lookup_elem(&dc_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->refs, 1ULL);
    } else {
        struct dc_stats var_2 = {};
        var_2.refs = 1ULL;
        bpf_map_update_elem(&dc_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("kprobe/d_lookup")
int kprobe_d_lookup(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct dc_stats *entry_1 = bpf_map_lookup_elem(&dc_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->slow, 1ULL);
    } else {
        struct dc_stats var_2 = {};
        var_2.slow = 1ULL;
        bpf_map_update_elem(&dc_stats, &var_0, &var_2, 1);
    }
    return 0;
}
