// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

struct cgroup_key {
    __u64 cgroup_id;
};

struct exec_stats {
    __u64 execs;
    __u64 exits;
    __u64 forks;
};

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct exec_stats);
} exec_stats SEC(".maps");

SEC("tp/sched/sched_process_exec")
int tp_sched_sched_process_exec(void *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct exec_stats *entry_1 = bpf_map_lookup_elem(&exec_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->execs, 1ULL);
    } else {
        struct exec_stats var_2 = {};
        var_2.execs = 1ULL;
        bpf_map_update_elem(&exec_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("tp/sched/sched_process_exit")
int tp_sched_sched_process_exit(void *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct exec_stats *entry_1 = bpf_map_lookup_elem(&exec_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->exits, 1ULL);
    } else {
        struct exec_stats var_2 = {};
        var_2.exits = 1ULL;
        bpf_map_update_elem(&exec_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("tp/sched/sched_process_fork")
int tp_sched_sched_process_fork(void *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct exec_stats *entry_1 = bpf_map_lookup_elem(&exec_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->forks, 1ULL);
    } else {
        struct exec_stats var_2 = {};
        var_2.forks = 1ULL;
        bpf_map_update_elem(&exec_stats, &var_0, &var_2, 1);
    }
    return 0;
}
