// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

struct cgroup_key {
    __u64 cgroup_id;
};

struct file_stats {
    __u64 creates;
    __u64 deletes;
};

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct file_stats);
} file_stats SEC(".maps");

SEC("kprobe/vfs_create")
int kprobe_vfs_create(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct file_stats *entry_1 = bpf_map_lookup_elem(&file_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->creates, 1ULL);
    } else {
        struct file_stats var_2 = {};
        var_2.creates = 1ULL;
        bpf_map_update_elem(&file_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("kprobe/vfs_unlink")
int kprobe_vfs_unlink(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct file_stats *entry_1 = bpf_map_lookup_elem(&file_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->deletes, 1ULL);
    } else {
        struct file_stats var_2 = {};
        var_2.deletes = 1ULL;
        bpf_map_update_elem(&file_stats, &var_0, &var_2, 1);
    }
    return 0;
}
