// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

#define MAX_ENTRIES 10240
#define MAX_SLOTS 27

static __always_inline __u32 log2l(__u64 v) {
    __u32 r = 0;
    while (v > 1) {
        v >>= 1;
        r++;
    }
    return r;
}

struct hist_key {
    __u64 cgroup_id;
};

struct hist_value {
    __u64 slots[27];
    __u64 count;
    __u64 sum_ns;
};

struct cgroup_key {
    __u64 cgroup_id;
};

struct counter {
    __u64 count;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 10240);
    __type(key, __u32);
    __type(value, __u64);
} wakeup_ts SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct hist_key);
    __type(value, struct hist_value);
} runq_latency SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct counter);
} ctx_switches SEC(".maps");

SEC("tp/sched/sched_wakeup")
int tp_sched_sched_wakeup(void *ctx)
{
    __u32 pid = ((struct trace_event_raw_sched_wakeup_template *)ctx)->pid;
    __u64 ts = bpf_ktime_get_ns();
    bpf_map_update_elem(&wakeup_ts, &pid, &ts, 0);
    return 0;
}

SEC("tp/sched/sched_switch")
int tp_sched_sched_switch(void *ctx)
{
    __u32 next_pid = ((struct trace_event_raw_sched_switch *)ctx)->next_pid;
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct counter *entry_1 = bpf_map_lookup_elem(&ctx_switches, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->count, 1ULL);
    } else {
        struct counter var_2 = {};
        var_2.count = 1ULL;
        bpf_map_update_elem(&ctx_switches, &var_0, &var_2, 1);
    }
    __u64 *entry_3 = bpf_map_lookup_elem(&wakeup_ts, &next_pid);
    if (entry_3) {
        __u64 delta_ns = (bpf_ktime_get_ns() - *entry_3);
        bpf_map_delete_elem(&wakeup_ts, &next_pid);
        struct hist_key var_4 = {};
        var_4.cgroup_id = cgroup_id;
        struct hist_value *entry_5 = bpf_map_lookup_elem(&runq_latency, &var_4);
        if (entry_5) {
            __u32 slot = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
            __sync_fetch_and_add(&entry_5->slots[slot], 1ULL);
            __sync_fetch_and_add(&entry_5->count, 1ULL);
            __sync_fetch_and_add(&entry_5->sum_ns, delta_ns);
        } else {
            __u32 slot2 = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
            struct hist_value var_6 = {};
            var_6.count = 1ULL;
            var_6.sum_ns = delta_ns;
            __s32 _arr_set = (var_6.slots[slot2] = 1ULL, (__s32)0);
            bpf_map_update_elem(&runq_latency, &var_4, &var_6, 1);
        }
    }
    return 0;
}
