// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

#define MAX_ENTRIES 10240
#define MAX_SLOTS 27

static __always_inline __u32 log2l(__u64 v) {
    __u32 r = 0;
    while (v > 1) {
        v >>= 1;
        r++;
    }
    return r;
}

struct hist_key {
    __u64 cgroup_id;
};

struct hist_value {
    __u64 slots[27];
    __u64 count;
    __u64 sum_ns;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 10240);
    __type(key, __u64);
    __type(value, __u64);
} softirq_start SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct hist_key);
    __type(value, struct hist_value);
} softirq_latency SEC(".maps");

SEC("tp/irq/softirq_entry")
int tp_irq_softirq_entry(void *ctx)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    __u64 ts = bpf_ktime_get_ns();
    bpf_map_update_elem(&softirq_start, &pid_tgid, &ts, 0);
    return 0;
}

SEC("tp/irq/softirq_exit")
int tp_irq_softirq_exit(void *ctx)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    __u64 *entry_0 = bpf_map_lookup_elem(&softirq_start, &pid_tgid);
    if (entry_0) {
        __u64 delta_ns = (bpf_ktime_get_ns() - *entry_0);
        bpf_map_delete_elem(&softirq_start, &pid_tgid);
        __u64 cgroup_id = bpf_get_current_cgroup_id();
        struct hist_key var_1 = {};
        var_1.cgroup_id = cgroup_id;
        struct hist_value *entry_2 = bpf_map_lookup_elem(&softirq_latency, &var_1);
        if (entry_2) {
            __u32 slot = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
            __sync_fetch_and_add(&entry_2->slots[slot], 1ULL);
            __sync_fetch_and_add(&entry_2->count, 1ULL);
            __sync_fetch_and_add(&entry_2->sum_ns, delta_ns);
        } else {
            __u32 slot2 = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
            struct hist_value var_3 = {};
            var_3.count = 1ULL;
            var_3.sum_ns = delta_ns;
            __s32 _arr_set = (var_3.slots[slot2] = 1ULL, (__s32)0);
            bpf_map_update_elem(&softirq_latency, &var_1, &var_3, 1);
        }
    }
    return 0;
}
