// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

struct cgroup_key {
    __u64 cgroup_id;
};

struct counter {
    __u64 count;
};

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct counter);
} tcp_drops SEC(".maps");

SEC("kprobe/tcp_drop")
int kprobe_tcp_drop(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct counter *entry_1 = bpf_map_lookup_elem(&tcp_drops, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->count, 1ULL);
    } else {
        struct counter var_2 = {};
        var_2.count = 1ULL;
        bpf_map_update_elem(&tcp_drops, &var_0, &var_2, 1);
    }
    return 0;
}
