// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

#define MAX_ENTRIES 10240
#define MAX_SLOTS 27

static __always_inline __u32 log2l(__u64 v) {
    __u32 r = 0;
    while (v > 1) {
        v >>= 1;
        r++;
    }
    return r;
}

struct hist_key {
    __u64 cgroup_id;
};

struct hist_value {
    __u64 slots[27];
    __u64 count;
    __u64 sum_ns;
};

struct cgroup_key {
    __u64 cgroup_id;
};

struct counter {
    __u64 count;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 10240);
    __type(key, __u64);
    __type(value, __u64);
} conn_start SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct hist_key);
    __type(value, struct hist_value);
} conn_life SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct counter);
} conn_count SEC(".maps");

SEC("tp/sock/inet_sock_set_state")
int tp_sock_inet_sock_set_state(void *ctx)
{
    __s32 newstate = ((struct trace_event_raw_inet_sock_set_state *)ctx)->newstate;
    __u64 port_pair = (((__u64)((struct trace_event_raw_inet_sock_set_state *)ctx)->sport << 32ULL) | (__u64)((struct trace_event_raw_inet_sock_set_state *)ctx)->dport);
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    if ((newstate == 1)) {
        __u64 ts = bpf_ktime_get_ns();
        bpf_map_update_elem(&conn_start, &port_pair, &ts, 0);
        struct cgroup_key var_0 = {};
        var_0.cgroup_id = cgroup_id;
        struct counter *entry_1 = bpf_map_lookup_elem(&conn_count, &var_0);
        if (entry_1) {
            __sync_fetch_and_add(&entry_1->count, 1ULL);
        } else {
            struct counter var_2 = {};
            var_2.count = 1ULL;
            bpf_map_update_elem(&conn_count, &var_0, &var_2, 1);
        }
    }
    if ((newstate == 7)) {
        __u64 *entry_3 = bpf_map_lookup_elem(&conn_start, &port_pair);
        if (entry_3) {
            __u64 delta_ns = (bpf_ktime_get_ns() - *entry_3);
            bpf_map_delete_elem(&conn_start, &port_pair);
            struct hist_key var_4 = {};
            var_4.cgroup_id = cgroup_id;
            struct hist_value *entry_5 = bpf_map_lookup_elem(&conn_life, &var_4);
            if (entry_5) {
                __u32 slot = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
                __sync_fetch_and_add(&entry_5->slots[slot], 1ULL);
                __sync_fetch_and_add(&entry_5->count, 1ULL);
                __sync_fetch_and_add(&entry_5->sum_ns, delta_ns);
            } else {
                __u32 slot2 = log2l(delta_ns) >= 27 ? 26 : log2l(delta_ns);
                struct hist_value var_6 = {};
                var_6.count = 1ULL;
                var_6.sum_ns = delta_ns;
                __s32 _arr_set = (var_6.slots[slot2] = 1ULL, (__s32)0);
                bpf_map_update_elem(&conn_life, &var_4, &var_6, 1);
            }
        }
    }
    return 0;
}
