// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

struct cgroup_key {
    __u64 cgroup_id;
};

struct vfs_stats {
    __u64 reads;
    __u64 writes;
    __u64 opens;
    __u64 fsyncs;
};

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct vfs_stats);
} vfs_stats SEC(".maps");

SEC("kprobe/vfs_read")
int kprobe_vfs_read(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct vfs_stats *entry_1 = bpf_map_lookup_elem(&vfs_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->reads, 1ULL);
    } else {
        struct vfs_stats var_2 = {};
        var_2.reads = 1ULL;
        bpf_map_update_elem(&vfs_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("kprobe/vfs_write")
int kprobe_vfs_write(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct vfs_stats *entry_1 = bpf_map_lookup_elem(&vfs_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->writes, 1ULL);
    } else {
        struct vfs_stats var_2 = {};
        var_2.writes = 1ULL;
        bpf_map_update_elem(&vfs_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("kprobe/vfs_open")
int kprobe_vfs_open(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct vfs_stats *entry_1 = bpf_map_lookup_elem(&vfs_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->opens, 1ULL);
    } else {
        struct vfs_stats var_2 = {};
        var_2.opens = 1ULL;
        bpf_map_update_elem(&vfs_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("kprobe/vfs_fsync")
int kprobe_vfs_fsync(struct pt_regs *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct vfs_stats *entry_1 = bpf_map_lookup_elem(&vfs_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->fsyncs, 1ULL);
    } else {
        struct vfs_stats var_2 = {};
        var_2.fsyncs = 1ULL;
        bpf_map_update_elem(&vfs_stats, &var_0, &var_2, 1);
    }
    return 0;
}
