// AUTO-GENERATED by kotlin-ebpf-dsl — do not edit

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

char LICENSE[] SEC("license") = "GPL";

struct cgroup_key {
    __u64 cgroup_id;
};

struct wb_stats {
    __u64 starts;
    __u64 completions;
};

struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 10240);
    __type(key, struct cgroup_key);
    __type(value, struct wb_stats);
} wb_stats SEC(".maps");

SEC("tp/writeback/writeback_start")
int tp_writeback_writeback_start(void *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct wb_stats *entry_1 = bpf_map_lookup_elem(&wb_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->starts, 1ULL);
    } else {
        struct wb_stats var_2 = {};
        var_2.starts = 1ULL;
        bpf_map_update_elem(&wb_stats, &var_0, &var_2, 1);
    }
    return 0;
}

SEC("tp/writeback/writeback_written")
int tp_writeback_writeback_written(void *ctx)
{
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    struct cgroup_key var_0 = {};
    var_0.cgroup_id = cgroup_id;
    struct wb_stats *entry_1 = bpf_map_lookup_elem(&wb_stats, &var_0);
    if (entry_1) {
        __sync_fetch_and_add(&entry_1->completions, 1ULL);
    } else {
        struct wb_stats var_2 = {};
        var_2.completions = 1ULL;
        bpf_map_update_elem(&wb_stats, &var_0, &var_2, 1);
    }
    return 0;
}
